### ISSUE TITLE
Top2013

### ISSUE THREAD

**Issue by cptolemy** [THRASTRO/ephem.js#1]
Good morning :)

Great library and script. Could you please make a perl script for converting TOP2013 aswell?

Kind regards

**Comment by mgreter** [comment]
Sorry for the long delay, will probably happen very soon, already got a passing port after one day :)

**Comment by cptolemy** [comment]
Good morning,

It's a pleasure to meet you.

No problem. Better late than never :) I am looking forward to the release.

Take care,

CPtolemy

**Comment by mgreter** [comment]
Implementation has been added ✌️
